format = """
[â”Œâ”€â”€](bold 4)($username[@](bold 4)$hostname) ([{](bold 2)$directory[}](bold 2)) $git_branch$git_status$status$sudo$fill$cmd_duration $time
[â””â”€](bold 4)$character
"""

[username]
show_always = true
style_user = "bold 2"
style_root = "bold 1"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold 2"
format = "[$hostname]($style)"

[directory]
style = "bold 7"
format = "[$path]($style)"
truncation_length = 6
truncate_to_repo = false

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "îœ¥"
style = "bold 1"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bold 3"
format = '[ ï€™ Status --> ($all_status$ahead_behind )]($style)'
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®« "
up_to_date = "ï€Œ "
untracked  = "? "
modified   = "î©± "
deleted    = "âœ˜ "
stashed    = ""
staged     = ""
renamed    = ""

[status]
disabled = false
format = "[ Fatal ! $status]($style)"
style = "bold 5"

[cmd_duration]
min_time = 0
format = "â± [$duration]($style)"
style = "bold 3"

[character]
success_symbol = "[#](bold 2)"
error_symbol = "[#](bold 7)"

[sudo]
disabled = false
symbol = "sudo ğŸ”’ "

[time]
disabled = false
format = "Time: [$time]($style) "
time_format = "%H:%M:%S"
style = "bold 7"
